name: BeaconEssentials
version: ${project.version}
main: dev.thebeaconcrafter.beaconessentials.Beaconessentials
api-version: 1.16
authors: [ TheBeaconCrafter ]
description: Ein Essentials-Plugin, welches dir viel Arbeit abnimmt.
website: thebeaconcrafter.tk

commands:
  heal:
    description: Heilt dich.
    aliases: [healme]
  fly:
    description: Ändert deinen Flugmodus.
  spawn:
    aliases: [setspawn]
    description: Teleportiert dich zum Spawn.
  vanish:
    aliases: [v]
    description: Macht dich unsichtbar.
  help:
    aliases: [helpme]
    description: Ruft die Hilfeoptionen auf.
  noon:
    aliases: [mittag]
    description: Stellt die Zeit auf Mittag.
  day:
    aliases: [tag]
    description: Stellt die Zeit auf Tag.
  night:
    aliases: [nacht]
    description: Stellt die Zeit auf Nacht.
  midnight:
    aliases: [mitternacht]
    description: Stellt die Zeit auf Mitternacht.
  gamemode:
    aliases: [gm]
    description: Ändert deinen Spielmodus.

permissions:
  beacon.beaconessentials.heal:
    description: Mit dieser Berechtigung kannst du /heal nutzen.
    default: op
  beacon.beaconessentials.fly:
    description: Mit dieser Berechtigung kannst du /fly nutzen.
    default: op
  beacon.beaconessentials.spawn.set:
    description: Du kannst den Spawn setzen.
    default: op
  beacon.beaconessentials.vanish:
    description: Du kannst dich in den Vanish versetzen.
    default: op
  beacon.beaconessentials.rang.owner:
    description: Du erhältst den Owner-Rang in der Tablist.
    default: op
  beacon.beaconessentials.rang.admin:
    description: Du erhältst den Admin-Rang in der Tablist.
    default: not op
  beacon.beaconessentials.rang.vip:
    description: Du erhältst den VIP-Rang in der Tablist.
    default: not op
  beacon.beaconessentials.rang.vipplus:
    description: Du erhältst den VIP+-Rang in der Tablist.
    default: not op
  beacon.beaconessentials.rang.spieler:
    description: Du erhältst den Spieler-Rang in der Tablist.
    default: not op
  beacon.beaconessentials.rang.legende:
    description: Du erhältst den Legende-Rang in der Tablist.
    default: not op
  beacon.beaconessentials.time:
    description: Du kannst die Zeit umstellen.
    default: op
  beacon.beaconessentials.gamemode:
    description: Du kannst deinen Spielmodus umstellen.
    default: op